#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: dehumidifier
  friendly_name: Dehumidifier
  device_description: DIY Smart Dehumidifier

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: d1_mini
#  platformio_options:
#    upload_speed: 57600
#    upload_speed: 28800

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret backup_ap_password

web_server:
  port: 80

captive_portal:

logger:

api:

ota:


#############################################################
# Use-case specific code

switch:
  - platform: gpio
    name: Green
    id: pin_g
    pin: D7
  - platform: gpio
    name: Red
    id: pin_r
    pin: D6
  - platform: gpio
    name: Blue
    id: pin_b
    pin: D5
  - platform: gpio
    name: Out
    id: pin_out
    pin: D0
    inverted: true

i2c:

#sensor:
#  - platform: bh1750
#    name: "BH1750 Illuminance"
#    address: 0x23
#    measurement_time: 69
#    update_interval: 60s
