#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: dehumidifier
  friendly_name: Dehumidifier
  device_description: DIY Smart Dehumidifier

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: d1_mini
#  platformio_options:
#    upload_speed: 57600
#    upload_speed: 28800

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret backup_ap_password

web_server:
  port: 80

captive_portal:

logger:

api:

ota:


#############################################################
# Use-case specific code

switch:
  - platform: gpio
    name: "${friendly_name} Fan"
    id: pin_out
    pin: D0
    inverted: true

output:
  - platform: esp8266_pwm
    pin: D7
    frequency: 1000 Hz
    id: pin_g
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    id: pin_r
  - platform: esp8266_pwm
    pin: D5
    frequency: 1000 Hz
    id: pin_b
light:
  - platform: rgb
    name: "${friendly_name} RGB"
    red: pin_r
    green: pin_g
    blue: pin_b

i2c:

#sensor:
#  - platform: bh1750
#    name: "BH1750 Illuminance"
#    address: 0x23
#    measurement_time: 69
#    update_interval: 60s
