#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: dehumidifier
  friendly_name: Dehumidifier
  device_description: DIY Smart Dehumidifier

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m
#  platformio_options:
#    upload_speed: 57600
#    upload_speed: 28800

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret backup_ap_password

web_server:
  port: 80

captive_portal:

logger:

api:

ota:


#############################################################
# Use-case specific code

switch:
  - platform: gpio
    name: Relay
    id: relay
    pin: GPIO0
  - platform: gpio
    id: led
    pin: GPIO2
    inverted: true

interval:
  - interval: 1sec
    then:
      - switch.toggle: led