#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: officedoor
  friendly_name: Office Door
  device_description: Show Office Status

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret backup_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#############################################################
# M5Stick hardawre stuff

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led

# internal IR Transmitter
remote_transmitter:
  - pin:
      number: GPIO9
    carrier_duty_percent: 50%
    id: internal

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: True

time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    id: sntp_time


#############################################################
# Use-case specific code

binary_sensor:
  # HA will detect that this is pressed and set desk.request = on
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Button A
#    on_press:
#      then:
#        - light.turn_on: led1
#    on_release:
#      then:
#        - light.turn_off: led1
  # No use for button B?
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button B

text_sensor:
  - platform: homeassistant
    id: desk_state_monitor
    # name: "Room State Monitor"
    entity_id: sensor.room_state
    on_value:
      then:
        - lambda: |-
            ESP_LOGD("main", "Setting effect to %s", x.c_str());
            auto call = id(led1).turn_on();
            call.set_effect(x.c_str());
            call.perform();

light:
  - platform: monochromatic
    output:  builtin_led
    name: LED
    id: led1
    effects:
      - strobe:
          name: Rest
          colors:
            - state: False
              duration: 1000ms
            - state: False
              duration: 1000ms
      - strobe:
          name: Work
          colors:
            - state: True
              brightness: 50%
              duration: 1000ms
            - state: True
              brightness: 50%
              duration: 1000ms
      - strobe:
          name: Focus
          colors:
            - state: True
              brightness: 100%
              duration: 1000ms
            - state: True
              brightness: 50%
              duration: 1000ms

## AXP192 power management - must be present to initialize TFT power on
#sensor:
#  - platform: axp192
#    address: 0x34
#    i2c_id: bus_a
#    update_interval: 30s
#    battery_level:
#      name: "M5Stick Battery Level"
#      id: "m5stick_batterylevel"
#
#  - platform: wifi_signal
#    name: ${upper_devicename} WiFi Signal
#    id: wifi_dbm
#  - platform: uptime
#    name: ${upper_devicename} Uptime
