#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: esptest
  friendly_name: ESP Test ROM
  device_description: Test each of the I/O ports on the ESP chip

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret backup_ap_password

web_server:
  port: 80

captive_portal:

logger:

ota:

api:


#############################################################
# Use-case specific code

switch:
  - platform: gpio
    name: GPIO0
    id: gpio0
    pin: GPIO0
  - platform: gpio
    name: GPIO1
    id: gpio1
    pin: GPIO1
  # GPIO2 is also connected to on-board LED. On-board LED
  # uses inverted controls.
  - platform: gpio
    # inverted: true
    name: GPIO2
    id: gpio2
    pin: GPIO2
  - platform: gpio
    name: GPIO3
    id: gpio3
    pin: GPIO3
  - platform: gpio
    name: GPIO4
    id: gpio4
    pin: GPIO4
  - platform: gpio
    name: GPIO5
    id: gpio5
    pin: GPIO5
#    pin: GPIO6 - Flash Clock
#    pin: GPIO7 - Flash Data 0
#    pin: GPIO8 - Flash Data 1
#    pin: GPIO9 - Maybe flash in quad IO mode
#    pin: GPIO10 - Maybe flash in quad IO mode
#    pin: GPIO11 - Flash Command
  - platform: gpio
    name: GPIO12
    id: gpio12
    pin: GPIO12
  - platform: gpio
    name: GPIO13
    id: gpio13
    pin: GPIO13
  - platform: gpio
    name: GPIO14
    id: gpio14
    pin: GPIO14
  - platform: gpio
    name: GPIO15
    id: gpio15
    pin: GPIO15

#binary_sensor:
#  - platform: gpio
#    id: gpio2
#    internal: true
#    pin:
#      number: D2
#      mode: INPUT_PULLDOWN_16
