#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: senstick

esphome:
  name: $devicename
  comment: Sensor Stick
  platform: ESP8266
  board: d1_mini
  libraries:
    - Wire
    - SPI
    - https://github.com/wemos/LOLIN_HP303B_Library.git

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

web_server:
  port: 80

logger:

api:

ota:


#############################################################
# Use-case specific code

external_components:
  - source: components

i2c:

sensor:
  - platform: bh1750
    name: "$devicename illuminance"
    address: 0x23
    update_interval: 60s
  - platform: sht3xd
    temperature:
      name: "$devicename temperature"
    humidity:
      name: "$devicename humidity"
    address: 0x45
    update_interval: 60s
  - platform: sgp30
    eco2:
      name: "$devicename eco2"
      accuracy_decimals: 1
    tvoc:
      name: "$devicename tvoc"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 60s
  - platform: hp303b
    temperature:
      name: "$devicename temperature2"
    pressure:
      name: "$devicename pressure"
    address: 0x77
    update_interval: 60s
