#############################################################
# Generic ESPHome stuff

substitutions:
  devicename: tvcontrol
  friendly_name: TV Control
  device_description: WiFi TV Remote

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .localdomain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret backup_ap_password

web_server:
  port: 80

captive_portal:

logger:

ota:


#############################################################
# Use-case specific code

# Enable Home Assistant API
api:
  # password: "************"
  services:
    # TV
    - service: volume_up
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0E01F
    - service: volume_down
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0D02F
    - service: power_toggle
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E040BF
    - service: switch_source
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0807F
    - service: tv_hdmi_1
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38029
            code: [+4497,-4497,+552,-1657,+552,-1657,+552,-1657,+552,-552,+552,-552,+552,-552,+552,-552,+552,-552,+552,-1657,+552,-1657,+552,-1657,+552,-552,+552,-552,+552,-552,+552,-552,+552,-552,+552,-1657,+552,-552,+552,-552,+552,-1657,+552,-552,+552,-1657,+552,-1657,+552,-1657,+552,-552,+552,-1657,+552,-1657,+552,-552,+552,-1657,+552,-552,+552,-552,+552,-552,+552,-47858]
    - service: tv_hdmi_2
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38029
            code: [+4523,-4497,+552,-1709,+552,-1709,+552,-1709,+552,-579,+552,-579,+552,-579,+552,-579,+552,-579,+552,-1709,+552,-1709,+552,-1709,+552,-579,+552,-579,+552,-579,+552,-579,+552,-579,+552,-579,+552,-1709,+552,-1709,+552,-1709,+552,-1709,+552,-1709,+552,-579,+552,-1709,+552,-1709,+552,-579,+552,-579,+552,-579,+552,-579,+552,-579,+552,-1709,+552,-579,+552,-43993]
    # HDMI switch
    - service: hdmi_up
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BF00FF
    - service: hdmi_down
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BF20DF
    - service: hdmi_1  # chromecast
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BF609F
    - service: hdmi_2  # steam link
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BF50AF
    - service: hdmi_3  # ps4
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BF708F
    - service: hdmi_4  # switch
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BF906F
    - service: hdmi_5  # laptop
      then:
        - remote_transmitter.transmit_lg:
            data: 0x40BFB04F

remote_transmitter:
  pin: D3
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: D4
    inverted: true
  dump: all

binary_sensor:
  - platform: gpio
    id: tv_power
    internal: true
    pin:
      number: D2
      mode: INPUT_PULLDOWN_16

switch:
  - platform: template
    name: "Living Room TV"
    id: living_room_tv
    lambda: |-
      if (id(tv_power).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_off: tv_power
          then:
          - remote_transmitter.transmit_samsung:
              data: 0xE0E040BF
    turn_off_action:
      - if:
          condition:
            binary_sensor.is_on: tv_power
          then:
           - remote_transmitter.transmit_samsung:
              data: 0xE0E040BF
